package com.ProdeMaster.ApiGateWay.security;

import com.ProdeMaster.ApiGateWay.Config.JwtProperties;
import com.ProdeMaster.ApiGateWay.fixtures.TestTokenFactory;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.jsonwebtoken.Claims;
import io.jsonwebtoken.ExpiredJwtException;
import io.jsonwebtoken.JwtException;
import io.jsonwebtoken.MalformedJwtException;
import io.jsonwebtoken.UnsupportedJwtException;
import io.jsonwebtoken.security.SignatureException;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.core.io.Resource;
import org.springframework.core.io.ResourceLoader;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.List;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.when;

/**
 * Unit tests for {@link JwtTokenProvider}.
 *
 * The RSA public key is injected via a mocked {@link ResourceLoader} that returns
 * the key generated by {@link TestTokenFactory}.  No Spring context is started.
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("JwtTokenProvider")
class JwtTokenProviderTest {

    @Mock
    private ResourceLoader resourceLoader;

    @Mock
    private Resource pemResource;

    private JwtProperties jwtProperties;
    private JwtTokenProvider jwtTokenProvider;

    @BeforeEach
    void setUp() throws IOException {
        jwtProperties = new JwtProperties();
        jwtProperties.setIssuer(TestTokenFactory.ISSUER);
        jwtProperties.setAudience(TestTokenFactory.AUDIENCE);
        jwtProperties.setClockSkewSeconds(30);
        jwtProperties.setAlgorithmWhitelist(List.of("RS256", "RS384", "RS512"));
        jwtProperties.setLoggingVerbose(true);
        jwtProperties.setPublicKeyPath("classpath:certs/test-public.pem");

        byte[] pemBytes = TestTokenFactory.getPublicKeyPem().getBytes(StandardCharsets.UTF_8);
        when(resourceLoader.getResource(any())).thenReturn(pemResource);
        when(pemResource.getInputStream()).thenReturn(new ByteArrayInputStream(pemBytes));

        jwtTokenProvider = new JwtTokenProvider(resourceLoader, jwtProperties, new ObjectMapper());
        jwtTokenProvider.init();
    }

    // =========================================================================
    // Group 1: Happy path — valid token
    // =========================================================================

    @Nested
    @DisplayName("Valid token")
    class ValidTokenTests {

        @Test
        @DisplayName("Should return non-null Claims for a well-formed RS256 token")
        void shouldReturnClaimsForValidToken() {
            Claims claims = jwtTokenProvider.validateAndExtract(TestTokenFactory.generateValidToken()).block();

            assertThat(claims)
                    .as("Claims must be present for a valid token")
                    .isNotNull();
        }

        @Test
        @DisplayName("Should extract correct 'sub' claim")
        void shouldExtractSubjectFromValidToken() {
            Claims claims = jwtTokenProvider.validateAndExtract(TestTokenFactory.generateValidToken()).block();

            assertThat(claims.getSubject())
                    .as("Subject must match the token builder value")
                    .isEqualTo(TestTokenFactory.SUBJECT);
        }

        @Test
        @DisplayName("Should extract non-empty 'roles' list")
        void shouldExtractRolesFromValidToken() {
            Claims claims = jwtTokenProvider.validateAndExtract(TestTokenFactory.generateValidToken()).block();

            @SuppressWarnings("unchecked")
            List<String> roles = (List<String>) claims.get("roles");
            assertThat(roles)
                    .as("Roles claim must be a non-empty list")
                    .isNotEmpty()
                    .contains("ADMIN", "USER");
        }

        @Test
        @DisplayName("Should expose 'iat' and 'exp' claims")
        void shouldExposeIssuedAtAndExpiration() {
            Claims claims = jwtTokenProvider.validateAndExtract(TestTokenFactory.generateValidToken()).block();

            assertThat(claims.getIssuedAt())
                    .as("iat must be present")
                    .isNotNull();
            assertThat(claims.getExpiration())
                    .as("exp must be present and in the future")
                    .isNotNull()
                    .isInTheFuture();
        }

        @Test
        @DisplayName("Should confirm token is not expired")
        void shouldConfirmTokenIsNotExpired() {
            Claims claims = jwtTokenProvider.validateAndExtract(TestTokenFactory.generateValidToken()).block();

            assertThat(claims.getExpiration())
                    .as("Token must still be valid (expiration in the future)")
                    .isInTheFuture();
        }

        @Test
        @DisplayName("extractUserId should return 'sub' claim value")
        void shouldExtractUserIdViaHelper() {
            String userId = jwtTokenProvider
                    .extractUserId(TestTokenFactory.generateValidToken())
                    .block();

            assertThat(userId).isEqualTo(TestTokenFactory.SUBJECT);
        }

        @Test
        @DisplayName("extractRoles should return role list")
        void shouldExtractRolesViaHelper() {
            List<String> roles = jwtTokenProvider
                    .extractRoles(TestTokenFactory.generateValidToken())
                    .block();

            assertThat(roles)
                    .as("Helper must return the same roles embedded in the token")
                    .containsExactlyInAnyOrderElementsOf(TestTokenFactory.ROLES);
        }
    }

    // =========================================================================
    // Group 2: Expired token
    // =========================================================================

    @Nested
    @DisplayName("Expired token")
    class ExpiredTokenTests {

        @Test
        @DisplayName("Should throw ExpiredJwtException for a token that expired 1 h ago")
        void shouldRejectExpiredToken() {
            String expired = TestTokenFactory.generateExpiredToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(expired).block())
                    .as("Expired token must trigger ExpiredJwtException")
                    .isInstanceOf(ExpiredJwtException.class);
        }

        @Test
        @DisplayName("ExpiredJwtException message must reference expiration")
        void expiredExceptionShouldHaveDescriptiveMessage() {
            String expired = TestTokenFactory.generateExpiredToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(expired).block())
                    .isInstanceOf(ExpiredJwtException.class)
                    .message()
                    .containsIgnoringCase("expir");
        }

        @Test
        @DisplayName("extractClaims should also throw ExpiredJwtException")
        void extractClaimsShouldThrowForExpiredToken() {
            String expired = TestTokenFactory.generateExpiredToken();

            assertThatThrownBy(() -> jwtTokenProvider.extractClaims(expired).block())
                    .isInstanceOf(ExpiredJwtException.class);
        }
    }

    // =========================================================================
    // Group 3: Malformed and invalid signature
    // =========================================================================

    @Nested
    @DisplayName("Malformed or signature-invalid token")
    class MalformedTokenTests {

        @Test
        @DisplayName("Should throw MalformedJwtException for a token with no dots")
        void shouldRejectTokenWithNoDots() {
            String malformed = TestTokenFactory.generateMalformedToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(malformed).block())
                    .isInstanceOf(MalformedJwtException.class);
        }

        @Test
        @DisplayName("Should throw SignatureException for corrupted signature bytes")
        void shouldRejectTokenWithInvalidSignature() {
            String badSig = TestTokenFactory.generateInvalidSignatureToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(badSig).block())
                    .isInstanceOf(SignatureException.class);
        }

        @Test
        @DisplayName("SignatureException message must be descriptive")
        void signatureExceptionShouldHaveDescriptiveMessage() {
            String badSig = TestTokenFactory.generateInvalidSignatureToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(badSig).block())
                    .isInstanceOf(SignatureException.class)
                    .message()
                    .isNotBlank();
        }
    }

    // =========================================================================
    // Group 4: Invalid mandatory claims
    // =========================================================================

    @Nested
    @DisplayName("Missing or invalid mandatory claims")
    class InvalidClaimsTests {

        @Test
        @DisplayName("Should throw JwtException when 'sub' claim is absent")
        void shouldRejectTokenWithoutSubject() {
            String noSub = TestTokenFactory.generateNoSubjectToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(noSub).block())
                    .as("Missing sub must cause JwtException")
                    .isInstanceOf(JwtException.class)
                    .message()
                    .containsIgnoringCase("sub");
        }

        @Test
        @DisplayName("Should throw JwtException when 'roles' claim is absent")
        void shouldRejectTokenWithoutRoles() {
            String noRoles = TestTokenFactory.generateNoRolesToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(noRoles).block())
                    .isInstanceOf(JwtException.class)
                    .message()
                    .containsIgnoringCase("roles");
        }

        @Test
        @DisplayName("Should throw JwtException when 'roles' claim is an empty list")
        void shouldRejectTokenWithEmptyRoles() {
            String emptyRoles = TestTokenFactory.generateEmptyRolesToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(emptyRoles).block())
                    .isInstanceOf(JwtException.class)
                    .message()
                    .containsIgnoringCase("roles");
        }

        @Test
        @DisplayName("Should throw JwtException when 'iat' claim is absent")
        void shouldRejectTokenWithoutIssuedAt() {
            String noIat = TestTokenFactory.generateNoIatToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(noIat).block())
                    .isInstanceOf(JwtException.class)
                    .message()
                    .containsIgnoringCase("iat");
        }
    }

    // =========================================================================
    // Group 5: Wrong issuer / audience
    // =========================================================================

    @Nested
    @DisplayName("Wrong issuer or audience")
    class WrongIssuerAudienceTests {

        @Test
        @DisplayName("Should throw JwtException when 'iss' does not match")
        void shouldRejectWrongIssuer() {
            String wrongIss = TestTokenFactory.generateWrongIssuerToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(wrongIss).block())
                    .as("Token with wrong issuer must be rejected")
                    .isInstanceOf(JwtException.class);
        }

        @Test
        @DisplayName("Should throw JwtException when 'aud' does not match")
        void shouldRejectWrongAudience() {
            String wrongAud = TestTokenFactory.generateWrongAudienceToken();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(wrongAud).block())
                    .as("Token with wrong audience must be rejected")
                    .isInstanceOf(JwtException.class);
        }
    }

    // =========================================================================
    // Group 6: Algorithm confusion attack prevention
    // =========================================================================

    @Nested
    @DisplayName("Algorithm confusion attack prevention")
    class AlgorithmConfusionTests {

        @Test
        @DisplayName("Should throw UnsupportedJwtException for HS256-signed token")
        void shouldRejectHS256Token() {
            String hs256 = TestTokenFactory.generateHS256Token();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(hs256).block())
                    .as("HS256 token must be rejected — only RS256/RS384/RS512 are allowed")
                    .isInstanceOf(UnsupportedJwtException.class);
        }

        @Test
        @DisplayName("UnsupportedJwtException message must mention algorithm rejection or confusion")
        void algorithmConfusionMessageMustBeExplicit() {
            String hs256 = TestTokenFactory.generateHS256Token();

            assertThatThrownBy(() -> jwtTokenProvider.validateAndExtract(hs256).block())
                    .isInstanceOf(UnsupportedJwtException.class)
                    .message()
                    .isNotBlank();
        }

        @Test
        @DisplayName("RS256 token must pass the algorithm whitelist check")
        void shouldAcceptRS256Token() {
            Claims claims = jwtTokenProvider.validateAndExtract(TestTokenFactory.generateValidToken()).block();

            assertThat(claims).isNotNull();
        }
    }

    // =========================================================================
    // Group 7: extractClaims utility
    // =========================================================================

    @Nested
    @DisplayName("extractClaims utility")
    class ExtractClaimsTests {

        @Test
        @DisplayName("Should return complete Claims for a valid token")
        void shouldReturnCompleteClaimsForValidToken() {
            Claims claims = jwtTokenProvider.extractClaims(TestTokenFactory.generateValidToken()).block();

            assertThat(claims)
                    .isNotNull();
            assertThat(claims.getSubject()).isEqualTo(TestTokenFactory.SUBJECT);
            assertThat(claims.getIssuer()).isEqualTo(TestTokenFactory.ISSUER);
            assertThat(claims.getIssuedAt()).isNotNull();
            assertThat(claims.getExpiration()).isNotNull();
        }

        @Test
        @DisplayName("extractClaims should surface roles claim directly")
        void shouldExposeRolesViaClaims() {
            Claims claims = jwtTokenProvider.extractClaims(TestTokenFactory.generateValidToken()).block();

            assertThat(claims.get("roles")).isNotNull();
        }

        @Test
        @DisplayName("extractClaims should throw for invalid signature")
        void shouldThrowForInvalidSignatureOnExtract() {
            String badSig = TestTokenFactory.generateInvalidSignatureToken();

            assertThatThrownBy(() -> jwtTokenProvider.extractClaims(badSig).block())
                    .isInstanceOf(SignatureException.class);
        }
    }
}
